# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIClientExample' do
  use_frameworks!

  pod 'APIClient', :path => '../../', :subspecs => ['Core', 'Genome']
end
